Fix error.
The code runs into the error:

TypeError: object of type 'method' has no len()

Adding the parenthesis solves the error. I don't know if there have been any changes in the dgl API but batch_num_nodes is a method, not an attribute.